name: built
description: A Workout Mobile App. 

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^2.0.0

flutter:

  
  uses-material-design: true

  assets:
   - assets/images/splash_screen.png
   - assets/images/1.jpg
   - assets/images/2.jpeg
   - assets/images/3.jpeg
   - assets/images/4.jpeg
   - assets/images/5.jpg
   - assets/images/6.jpg
   - assets/images/7.jpg
   - assets/images/8.jpg
   - assets/images/logo.png
   - assets/icons/nav_icon/collection.png
   - assets/icons/nav_icon/home.png
   - assets/icons/nav_icon/analytics.png
   - assets/icons/nav_icon/settings.png

  #   - images/a_dot_ham.jpeg

  
  # fonts:
  #   - family: Schylerss
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  

